apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: default
  labels:
    lab: devops
spec:
  containers:
  - name: nginx
    image: nginx:1.25.3
    ports:
    - containerPort: 80
      protocol: TCP

